[workspace]
members = [
    "crates//kfuz2_cli",
    "crates//kfuz2_egui",
    "crates//kfuz2_lib",
    "crates//tests",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true
