# Contains lists with vanilla packages

vanillaAnimations: list[str] = ['22PatchMesh.ukx', 'Foundry_anim.ukx', 'FrightYard_SKM.ukx', 'Gear_anm.ukx', 'HillbillyHorror_anim.ukx',
                                'KFBoss.ukx', 'KFCharacterModels.ukx', 'KFCharactersB.ukx', 'KFMapObjects.ukx', 'KFSoldiers.ukx',
                                'KFVehicleModels.ukx', 'KFWeaponModels.ukx', 'KF_Freaks2_Trip.ukx', 'KF_Freaks2_Trip_CIRCUS.ukx',
                                'KF_Freaks2_Trip_Halloween.ukx', 'KF_Freaks2_Trip_Xmas.ukx', 'KF_Freaks_Trip.ukx',
                                'KF_Freaks_Trip_CIRCUS.ukx', 'KF_Freaks_Trip_Halloween.ukx', 'KF_Freaks_Trip_Xmas.ukx',
                                'KF_Gibbs_Trip.ukx', 'KF_IJC_Halloween_Weps3.ukx', 'KF_IJC_Halloween_Weps_2.ukx', 'KF_IJC_Summer_Weps1.ukx',
                                'KF_MAC10MPAnims.ukx', 'KF_RachelC_anim.ukx', 'KF_RingMaster_Trip.ukx', 'KF_RobotDance.ukx',
                                'KF_Soldier_Trip.ukx', 'KF_Weapons2_Trip.ukx', 'KF_Weapons3rd2_IJC.ukx', 'KF_Weapons3rd2_Trip.ukx',
                                'KF_Weapons3rd3_IJC.ukx', 'KF_Weapons3rd3_Trip.ukx', 'KF_Weapons3rd4_Trip.ukx', 'KF_Weapons3rd5_Trip.ukx',
                                'KF_Weapons3rd6_Trip.ukx', 'KF_Weapons3rd_IJC.ukx', 'KF_Weapons3rd_Trip.ukx', 'KF_Weapons_Trip.ukx',
                                'KF_Wep_Benelli.ukx', 'KF_Wep_Claymore.ukx', 'KF_Wep_DualRevolver.ukx', 'KF_Wep_Dual_MK23.ukx',
                                'KF_Wep_Dwarf_Axe.ukx', 'KF_Wep_Fal_Acog.ukx', 'KF_Wep_HuskGun.ukx', 'KF_Wep_Kriss.ukx',
                                'KF_Wep_KSG_Shotgun.ukx', 'KF_Wep_M4.ukx', 'KF_Wep_M4M203.ukx', 'KF_Wep_M7A3.ukx', 'KF_Wep_M99_Sniper.ukx',
                                'KF_Wep_MedicNade.ukx', 'KF_Wep_MK23.ukx', 'KF_Wep_MKB42.ukx', 'KF_Wep_MP5.ukx', 'KF_Wep_Revolver.ukx',
                                'KF_Wep_TrenchGun.ukx', 'KF_Wep_Vlad9000.ukx', 'KF_Wep_ZEDGun.ukx', 'KF_Wp3rdCAMO_Trip.ukx',
                                'KF_Wp3rdGold_Trip.ukx', 'Patch2Anims.ukx', 'Pier_anim.ukx', 'Yahct_Anim.ukx']

vanillaSounds: list[str]     = ['AbusementParkSND.uax', 'AmbOutside.uax', 'Amb_Animals.uax', 'Amb_Constructions.uax',
                                'Amb_ConstructionsTwo.uax', 'Amb_Destruction.uax', 'Amb_Destruction2.uax', 'Amb_Vehicles.uax',
                                'Amb_Weather.uax', 'Amb_Weather01.uax', 'Amb_Weather02.uax', 'Artillery.uax', 'FreakCircus_Snd_two.uax',
                                'Frightyard_snd.uax', 'Hellride_Snd.uax', 'HillbillyHorrorSND.uax', 'Inf_Player.uax', 'Inf_Weapons.uax',
                                'Inf_WeaponsTwo.uax', 'Inf_Weapons_Foley.uax', 'Inf_Weapons_Foley2.uax', 'Inf_Weapons_Foley_3rd.uax',
                                'KFAmbientSound.uax', 'KFPawnDamageSound.uax', 'KFPlayerSound.uax', 'kfportal_snd.uax', 'KFWeaponSound.uax',
                                'KF_9MMSnd.uax', 'KF_AA12Snd.uax', 'KF_AK47Snd.uax', 'KF_AxeSnd.uax', 'KF_BaseBloat.uax',
                                'KF_BaseBloat_CIRCUS.uax', 'KF_BaseBloat_HALLOWEEN.uax', 'KF_BaseBloat_xmas.uax', 'KF_BaseClot.uax',
                                'KF_BaseClot_CIRCUS.uax', 'KF_BaseClot_HALLOWEEN.uax', 'KF_BaseClot_xmas.uax', 'KF_BaseCrawler.uax',
                                'KF_BaseCrawler_CIRCUS.uax', 'KF_BaseCrawler_HALLOWEEN.uax', 'KF_BaseCrawler_Xmas.uax', 'KF_BaseFleshpound.uax',
                                'KF_BaseFleshpound_CIRCUS.uax', 'KF_BaseFleshpound_HALLOWEEN.uax', 'KF_BaseFleshpound_Xmas.uax',
                                'KF_BaseGorefast.uax', 'KF_BaseGorefast_CIRCUS.uax', 'KF_BaseGorefast_HALLOWEEN.uax', 'KF_BaseGorefast_xmas.uax',
                                'KF_BaseHusk.uax', 'KF_BaseHusk_CIRCUS.uax', 'KF_BaseHusk_HALLOWEEN.uax', 'KF_BaseHusk_Xmas.uax',
                                'KF_BasePatriarch.uax', 'KF_BasePatriarchTwo.uax', 'KF_BasePatriarch_CIRCUS.uax', 'KF_BasePatriarch_HALLOWEEN.uax',
                                'KF_BasePatriarch_xmas.uax', 'KF_BaseScrake.uax', 'KF_BaseScrake_CIRCUS.uax', 'KF_BaseScrake_HALLOWEEN.uax',
                                'KF_BaseScrake_Xmas.uax', 'KF_BaseSiren.uax', 'KF_BaseSiren_CIRCUS.uax', 'KF_BaseSiren_HALLOWEEN.uax',
                                'KF_BaseSiren_Xmas.uax', 'KF_BaseStalker.uax', 'KF_BaseStalker_CIRCUS.uax', 'KF_BaseStalker_HALLOWEEN.uax',
                                'KF_BaseStalker_Xmas.uax', 'KF_BImpactSnd.uax', 'KF_BullpupSnd.uax', 'KF_ChainsawSnd.uax',
                                'KF_ChainsawSnd_Xmas.uax', 'KF_ClaymoreSnd.uax', 'KF_DARVoice.uax', 'KF_DoubleSGSnd.uax', 'KF_DwarfAxeSnd.uax',
                                'KF_EnemiesFinalSnd.uax', 'KF_EnemiesFinalSnd_CIRCUS.uax', 'KF_EnemiesFinalSnd_HALLOWEEN.uax',
                                'KF_EnemiesFinalSnd_Xmas.uax', 'KF_EnemyGlobalSnd.uax', 'KF_EnemyGlobalSndTwo.uax', 'KF_EnvAmbientSnd.uax',
                                'KF_EnvAmbientSnd2.uax', 'KF_FemaleVoiceOne.uax', 'KF_FlamethrowerSnd.uax', 'KF_FNFALSnd.uax', 'KF_FoundrySnd.uax',
                                'KF_FY_BlowerThrowerSND.uax', 'KF_FY_SealSquealSND.uax', 'KF_FY_SeekerSixSND.uax', 'KF_FY_ZEDV2SND.uax',
                                'KF_GrenadeSnd.uax', 'KF_HandcannonSnd.uax', 'KF_HuskGunSnd.uax', 'KF_IJC_HalloweenSnd.uax', 'KF_IndoorAmb1.uax',
                                'KF_InterfaceSnd.uax', 'KF_InventorySnd.uax', 'KF_JumpSnd.uax', 'KF_KatanaSnd.uax', 'KF_KnifeSnd.uax',
                                'KF_KrissSND.uax', 'KF_KSGSnd.uax', 'KF_LAWSnd.uax', 'KF_M14EBRSnd.uax', 'KF_M32Snd.uax', 'KF_M4RifleSnd.uax',
                                'KF_M4ShotgunSnd.uax', 'KF_M79Snd.uax', 'KF_M7A3Snd.uax', 'KF_M99Snd.uax', 'KF_MAC10MPSnd.uax', 'KF_MacheteSnd.uax',
                                'KF_MaleVoiceOne.uax', 'KF_MaleVoiceTwo.uax', 'KF_MedicGrenadeSnd.uax', 'KF_MenuSnd.uax', 'KF_MK23Snd.uax',
                                'KF_mkb42Snd.uax', 'KF_MP5Snd.uax', 'KF_MP7Snd.uax', 'KF_MumbleVoice.uax', 'KF_NailShotgun.uax', 'KF_OutdoorAmb1.uax',
                                'KF_PipeSnd.uax', 'KF_PlayerGlobalSnd.uax', 'KF_PlayerM1Voc.uax', 'KF_PumpSGSnd.uax', 'KF_RevolverSnd.uax',
                                'KF_RifleSnd.uax', 'KF_RS_ThompsonSnd.uax', 'KF_SCARSnd.uax', 'KF_ShotgunDragonsBreathSnd.uax',
                                'KF_SP_LongmusketSnd.uax', 'KF_SP_OrcaSnd.uax', 'KF_SP_ThompsonSnd.uax', 'KF_SP_ZEDThrowerSnd.uax',
                                'KF_Swansong_SND.uax', 'KF_Trader.uax', 'KF_Transit_Dialog_SND.uax', 'KF_XbowSnd.uax', 'KF_ZEDGunSnd.uax',
                                'Miscsounds.uax', 'PatchSounds.uax', 'ProjectileSounds.uax', 'ROMenuSounds.uax', 'Steamland_SND.uax',
                                'SummerBoardwalkDialogue.uax', 'Vehicle_Engines.uax', 'Vehicle_Weapons.uax', 'WoodBreakFX.uax']

vanillaStaticMeshes: list[str] = ['22Patch.usx', 'Asylum_SM.usx', 'BaksanValleySM.usx', 'CivilVehicles_SM.usx', 'DebugObjects.usx',
                                  'DepartedStatics.usx', 'DetailSM.usx', 'EffectsSM.usx', 'FallenHerosSM.usx', 'Filthscross_SM.usx',
                                  'Foundry_SM.usx', 'FreakCircus_SM_One.usx', 'FreakCircus_SM_Two.usx', 'FrightYard2_SM.usx', 'FrightYard_SM.usx',
                                  'FurnitureSM.usx', 'GKStaticMeshes.usx', 'HedgehogSM.usx', 'Hellride_SM.usx', 'HemispheresSM.usx',
                                  'HemispheresSM2.usx', 'HillbillyHorror_SM.usx', 'Icebreaker_SM.usx', 'IJCWeaponPackStaticsW2.usx',
                                  'IndustrySM.usx', 'IndustrySM2.usx', 'KesselSM.usx', 'KFMuzzleFlashes.usx', 'kfportal_SM.usx',
                                  'KF_Enginetest.usx', 'KF_FX_Char_SM.usx', 'kf_generic_sm.usx', 'kf_gore_trip_sm.usx', 'kf_gore_trip_sm_CIRCUS.usx',
                                  'kf_gore_trip_sm_HALLOWEEN.usx', 'kf_gore_trip_sm_two.usx', 'kf_gore_trip_sm_xmas.usx', 'KF_icetunnel_SM.usx',
                                  'KF_IJC_Halloween_Weps.usx', 'KF_IJC_Halloween_Weps2.usx', 'KF_IJC_Summer_Weps.usx', 'KF_pickups2_Trip.usx',
                                  'KF_pickups3_Trip.usx', 'KF_pickups4_Trip.usx', 'KF_pickups5_Trip.usx', 'KF_pickups6_Trip.usx',
                                  'KF_pickupsCAMO_Trip.usx', 'KF_pickupsGold_Trip.usx', 'KF_pickups_Trip.usx', 'KF_SirensBelch_SM.usx',
                                  'KF_Swansong_SM.usx', 'KillingFloorLabStatics.usx', 'KillingFloorManorStatics.usx', 'KillingFloorStatics.usx',
                                  'KonigsPlatzSM.usx', 'KrasnyiSM.usx', 'KrasnyiSM2.usx', 'LandscapeSM.usx', 'LevelSpecificSM.usx',
                                  'LevelSpecificSM2.usx', 'MenuStatics.usx', 'Moonbase_SM.usx', 'Moonbase_SM_two.usx', 'MountainPass_SM.usx',
                                  'MrsFoster_DLC_Gore_SM.usx', 'MrsFoster_Steampunk_DLC_Gore_SM.usx', 'NewPatchSM.usx', 'OfficeStatics.usx',
                                  'PatchStatics.usx', 'Pier_SM.usx', 'Potato_S.usx', 'Props_ObjectiveMode.usx', 'ReligiousSM.usx', 'RuralSM.usx',
                                  'SpecialEffectsSM.usx', 'Stronghold_SM.usx', 'VegetationSM.usx', 'VegetationSM_Two.usx', 'Waterworks_SM.usx',
                                  'Workshop_SM.usx', 'WyreStatics.usx', 'ZED_FX_SM.usx', 'ZED_Pieces.usx']

vanillaSystem: list[str] = ['Core.u', 'Editor.u', 'Engine.u', 'Fire.u', 'FrightScript.u', 'GamePlay.u', 'GoodKarma.u',
                            'GUI2K4.u', 'IpDrv.u', 'KFChar.u', 'KFGui.u', 'KFMod.u', 'KFMutators.u', 'KFStoryGame.u',
                            'KFStoryUI.u', 'Old2k4.u', 'ROEffects.u', 'ROEngine.u', 'ROInterface.u', 'SideshowScript.u',
                            'UnrealEd.u', 'UnrealGame.u', 'UTV2004c.u', 'UTV2004s.u', 'UWeb.u', 'XAdmin.u', 'XGame.u', 'XInterface.u',
                            'XVoting.u', 'XWebAdmin.u']

vanillaTextures: list[str] = ['20Credits.utx', '22CharTex.utx', '25Tex.utx', '2K4Menus.utx', 'Architecture_T.utx', 'Architecture_T2.utx',
                              'Architecture_T3.utx', 'Asylum_T.utx', 'Baksanvalley_T.utx', 'CellExample.utx', 'Characters_tex.utx',
                              'CivilVehicles_SMT.utx', 'Crash_T.utx', 'Danzig_T.utx', 'Danzig_T2.utx', 'Danzig_T3.utx', 'DepartedTextures.utx',
                              'DetailSMT.utx', 'Detailtextures_T.utx', 'DreamTex.utx', 'Effects_Tex.utx', 'Effects_Tex_Steampunk.utx',
                              'FallenHeros2_T.utx', 'Filthscross_T.utx', 'Foundry_T.utx', 'FreakCircus_T_One.utx', 'FreakCircus_T_two.utx',
                              'FrightYard2_T.utx', 'FrightYard_T.utx', 'FurnitureSMT.utx', 'G15LCD.utx', 'G15LCDFonts.utx', 'Gear_tex.utx',
                              'GKTextures.utx', 'Hedgehog_T.utx', 'Hellride_T.utx', 'Hemispheres_SMT.utx', 'Hemispheres_SMT2.utx',
                              'HillbillyHorror_T.utx', 'Icebreaker_T.utx', 'IJCFonts.utx', 'IndustrySMT.utx', 'IndustrySMT2.utx',
                              'InterfaceArt2_tex.utx', 'InterfaceArt_tex.utx', 'InterfaceContent.utx', 'Kessel_T.utx', 'KFCharacters.utx',
                              'KFFonts.utx', 'KFGui.utx', 'KFInterfaceContent.utx', 'KFKillMeNow.utx', 'KFLevelPreviews.utx',
                              'KFMapEndTextures.utx', 'KFMaterials.utx', 'KFPatch2.utx', 'kfportal_T.utx', 'KFPortraits.utx',
                              'KFStoryGame_Tex.utx', 'KFThumbs.utx', 'KFUrbanSkin.utx', 'KFX.utx', 'KFZED_FX_T.utx', 'KF_DLC.utx',
                              'KF_FX_Char_T.utx', 'kf_fx_trip_t.utx', 'kf_generic_t.utx', 'kf_gore_trip_T_two.utx', 'KF_icetunnel_T.utx',
                              'KF_IJC_Halloween_Weapons.utx', 'KF_IJC_Halloween_Weapons2.utx', 'KF_IJC_Halloween_Weapons2_3rd.utx',
                              'KF_IJC_Halloween_Weapons_3rd.utx', 'KF_IJC_HUD.utx', 'KF_IJC_Summer_Weapons.utx', 'KF_IJC_Summer_Weapons_3rd.utx',
                              'KF_InterfaceArt_tex.utx', 'KF_MAC10MPTex.utx', 'KF_RachelC_mat.utx', 'KF_SirensBelch_T.utx', 'KF_Soldier11_Trip_T.utx',
                              'KF_Soldier12_Trip_T.utx', 'KF_Soldier13_Trip_T.utx', 'KF_Soldier2_Trip_T.utx', 'KF_Soldier3_Trip_T.utx',
                              'KF_Soldier4_Trip_T.utx', 'KF_Soldier5_Trip_T.utx', 'KF_Soldier6_Trip_T.utx', 'KF_SoldierMagmaNeon_Trip_T.utx',
                              'KF_Soldier_Trip_T.utx', 'KF_Solider10_Trip_T.utx', 'KF_Solider7_Trip_T.utx', 'KF_Solider8_Trip_T.utx',
                              'KF_Solider9_Trip_T.utx', 'KF_Specimens_Trip_CIRCUS_T.utx', 'KF_Specimens_Trip_Halloween_T.utx',
                              'KF_Specimens_Trip_T.utx', 'KF_Specimens_Trip_T_Two.utx', 'KF_Specimens_Trip_XMAS_T.utx',
                              'KF_Specimens_Trip_XMAS_T_Two.utx', 'KF_Swansong_Tex.utx', 'KF_Weapons2_Trip_T.utx', 'KF_Weapons3rd2_Trip_T.utx',
                              'KF_Weapons3rd3_Trip_T.utx', 'KF_Weapons3rd4_Trip_T.utx', 'KF_Weapons3rd5_Trip_T.utx', 'KF_Weapons3rd6_Trip_T.utx',
                              'KF_Weapons3rd_camo_Trip_T.utx', 'KF_Weapons3rd_Gold_T.utx', 'KF_Weapons3rd_Trip_T.utx', 'KF_Weapons3_Trip_T.utx',
                              'KF_Weapons4_Trip_T.utx', 'KF_Weapons5_Scopes_Trip_T.utx', 'KF_Weapons5_Trip_T.utx', 'KF_Weapons6_Trip_T.utx',
                              'KF_Weapons7_Trip_T.utx', 'KF_Weapons8_Trip_T.utx', 'Kf_Weapons9_Trip_T.utx', 'Kf_Weapons_camo_Trip_T.utx',
                              'KF_Weapons_Gold_T.utx', 'KF_Weapons_Neon_Trip_T.utx', 'KF_Weapons_Trip_T.utx', 'KillingFloor2HUD.utx',
                              'KillingFloorHUD.utx', 'KillingFloorHUD_HALLOWEEN.utx', 'KillingFloorHUD_SUMMER.utx', 'KillingFloorHUD_XMAS.utx',
                              'KillingFloorLabTextures.utx', 'KillingFloorManorTextures.utx', 'KillingFloorOfficeTextures.utx',
                              'KillingFloorTextures.utx', 'KillingFloorWeapons.utx', 'KonigsPlatz_T.utx', 'KrasnyiOktyabr_T.utx',
                              'KrasnyiOktyabr_T2.utx', 'Krasnyi_Cubemaps.utx', 'LandscapeSMT.utx', 'Landscape_T.utx', 'LevelSpecificSMT.utx',
                              'LevelSpecificSMT2.utx', 'MenuBackground.utx', 'MilitaryAxisSMT.utx', 'MoonBase_T.utx', 'MoonBase_T_Two.utx',
                              'MountainPass_T.utx', 'MrsFoster_DLC_1stP.utx', 'MrsFoster_DLC_3rdP.utx', 'MrsFoster_Steampunk_DLC_1stP.utx',
                              'MrsFoster_Steampunk_DLC_3rdP.utx', 'ObjectiveMode_T.utx', 'PatchTex.utx', 'Pier_T.utx', 'Pitomnik_T.utx',
                              'Placeholder_T.utx', 'Potato_T.utx', 'ReligiousSMT.utx', 'Ringmaster_Lockheart_T.utx', 'ROFonts.utx', 'ROFontsTwo.utx',
                              'ROFonts_Rus.utx', 'ROInterfaceArt.utx', 'RSDLC_1stP.utx', 'RSDLC_3rdP.utx', 'RuralSMT.utx', 'ScopeShaders.utx',
                              'SpecialEffects.utx', 'Stronghold_T.utx', 'VegetationSMT.utx', 'VegetationSMT_two.utx', 'Waterworks_T.utx',
                              'Weapons1st_tex.utx', 'Workshop_T.utx', 'WyreTex.utx']