# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "kfuz2_lib"
authors.workspace = true
edition.workspace = true
version = "1.6.3"
rust-version.workspace = true
description = "Creates uz2 files and does it fast."
license = "GPL-3.0"
repository = "https://github.com/InsultingPros/KFRedirectTool/tree/main/crates/kfuz2_lib"
keywords = ["unreal"]
categories = ["compression"]

[lints]
workspace = true

[dependencies]
flate2 = { workspace = true }
thiserror = { workspace = true }
sha1_smol = "1"
phf = { version = "0.*", features = ["macros"] }
