# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "kfuz2_lib"
authors.workspace = true
edition.workspace = true
version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
flate2 = { version = "1.0.35", features = [
    "zlib-rs",
], default-features = false }
sha1_smol = "1"
thiserror = "2"
