name: Build Debug and Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  start:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    name: Start `cargo build / test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_INCREMENTAL: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - if: runner.os == 'Linux'
        name: Install missing `libgtk-3-dev`
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev

      - name: Set up Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust
          shared-key: kfuz2
          cache-targets: true
          cache-all-crates: true

      - name: Build Debug
        run: cargo build --locked --target ${{ matrix.target }}

      - name: Run CLI Tests
        run: cargo test --locked --target ${{ matrix.target }} -- --test-threads 1
