name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish-rust:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      id-token: write
      issues: write

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: kfuz2
            asset_name: kfuz2-linux-amd64
          - os: windows-latest
            artifact_name: kfuz2.exe
            asset_name: kfuz2-windows-amd64
          - os: macos-latest
            artifact_name: kfuz2
            asset_name: kfuz2-macos-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust Toolchain
        run: rustup toolchain install stable --profile minimal

      # can't use caches in tag scope... thanks github!
      - name: Publish Rust Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.# Note that glob pattern is not supported yet.
          bin: kfuz2
          include: kfuz2_tkinter_gui/src/tkinterGUI.py
          # (optional) On which platform to distribute the .tar.gz file.# [default value: unix]# [possible values: all, unix, windows, none]
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
