name: Publish

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  publish-github-binaries:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - if: runner.os == 'Linux'
        name: Install missing `libgtk-3-dev`
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev

      - name: Set up Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      # can't use caches in tag scope... thanks github!
      - name: Publish CLI Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          locked: true
          target: ${{ matrix.target }}
          bin: kfuz2_cli
          tar: unix
          zip: windows
          archive: $bin-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish EGUI Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          locked: true
          target: ${{ matrix.target }}
          bin: kfuz2_egui
          tar: unix
          zip: windows
          archive: $bin-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}

  crates_io_publish:
    name: Publish (crates.io)
    needs:
      - publish-github-binaries

    runs-on: macos-14
    timeout-minutes: 25
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo login
        run: |-
          echo "${{ secrets.CRATES_IO_API_TOKEN }}" | cargo login

      - name: "cargo release publish"
        run: cargo publish -p kfuz2_lib